alias rc="rails console"
alias rd="rails destroy"
alias rdb="rails dbconsole"
alias rg="rails generate"
alias rgm="rails generate migration"
alias rp="rails plugin"
alias ru="rails runner"
alias rs="rails server"
alias rsd="rails server --debugger"

alias rdm="rake db:migrate"
alias rdms="rake db:migrate:status"
alias rdr="rake db:rollback"
alias rdc="rake db:create"
alias rds="rake db:seed"
alias rdd="rake db:drop"
alias rdtc="rake db:test:clone"
alias rdtp="rake db:test:prepare"
alias rdmtc="rake db:migrate db:test:clone"
alias rlc="rake log:clear"
alias rn="rake notes"
alias rr="rake routes"

alias bi="bundle install"
alias bu="bundle update"
